# Generated by Django 5.2.3 on 2025-07-02 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_schema_delete_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schema",
            name="title",
        ),
        migrations.AddField(
            model_name="schema",
            name="name",
            field=models.CharField(
                default="noexist",
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name must be in the format lowercase.lowercase...",
                        regex="^[a-z0-9]+(\\.[a-z0-9]+)*$",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schema",
            name="description",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="schema",
            name="yaml",
            field=models.TextField(default=""),
        ),
    ]
