# Generated by Django 5.2.3 on 2025-07-02 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_schema_title_schema_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schema",
            name="id",
        ),
        migrations.AlterField(
            model_name="schema",
            name="name",
            field=models.CharField(
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name must be in the format lowercase.lowercase...",
                        regex="^[a-z0-9]+(\\.[a-z0-9]+)*$",
                    )
                ],
            ),
        ),
    ]
