# Generated by Django 5.2.4 on 2025-07-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_schema_id_alter_schema_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Stock keeping unit name", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Description")),
                (
                    "gpl",
                    models.CharField(
                        default="pcs",
                        help_text="Unit of measure (e.g., pcs, kg, m)",
                        max_length=20,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("hardware", "Hardware"),
                            ("software", "Software"),
                            ("a-care", "A-Care"),
                            ("cvp", "CVP"),
                            ("licenses", "Licenses"),
                        ],
                        help_text="Product classification",
                        max_length=20,
                    ),
                ),
                (
                    "gpl_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional GPL (Global Price List) price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
