# Generated by Django 5.2.4 on 2025-07-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="updated_at",
        ),
    ]
